spring:
  mail:
    host: smtp.163.com
    username: 17850096172@163.com
    password: WAmB77xjzsvwkaxR
  rabbitmq:
    addresses: 192.168.56.102
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: password
      expire: 7
      limit:
        base: 10
        upgrade: 300
        frequency: 30
  data:
    redis:
      host: 192.168.56.102
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
